version '2'
services:
    db-members:
        image: 'postgres:9.6'
        autorestart: always
        environment: 
            - POSTGRES_USER=members 
            - POSTGRES_PASSWORD=J5brHrAXFLQSif0K 
            - POSTGRES_DB=members

    lb-members:
        image: 'dockercloud/haproxy:latest'
        autorestart: always
        links:
            - members
        ports: 
            - "80:80"
        roles:
            - global


    members:
        image: 'chamaconektkenya/members:latest'
        autorestart: always
        links: 
            - postgres
        deployment_strategy: high_availability
        target_num_containers: 4






